# Generated by Django 5.2.1 on 2025-06-08 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('address', models.TextField()),
                ('capacity', models.PositiveIntegerField(help_text='Maximum number of guests')),
                ('venue_type', models.CharField(choices=[('restaurant', 'Restaurant PDR'), ('hotel', 'Hotel'), ('event_hall', 'Event Hall'), ('garden', 'Garden'), ('beachside', 'Beachside'), ('heritage', 'Heritage House'), ('other', 'Other')], max_length=15)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('booking_policy', models.TextField(blank=True)),
                ('cancellation_policy', models.TextField(blank=True)),
                ('corkage_policy', models.TextField(blank=True, help_text='Policy for bringing outside food/drinks')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base price for venue rental', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='accounts.providerprofile')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VenueFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='venues.venue')),
            ],
        ),
        migrations.CreateModel(
            name='VenueImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='venue_images/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='venues.venue')),
            ],
        ),
        migrations.CreateModel(
            name='VenueRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('has_av_equipment', models.BooleanField(default=False)),
                ('has_stage', models.BooleanField(default=False)),
                ('available_layouts', models.CharField(help_text='Comma-separated list of available layouts', max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Price for this room specifically (if different from venue base price)', max_digits=10, null=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='venues.venue')),
            ],
        ),
        migrations.CreateModel(
            name='VenueAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('morning_available', models.BooleanField(default=True)),
                ('afternoon_available', models.BooleanField(default=True)),
                ('evening_available', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='venues.venue')),
            ],
            options={
                'verbose_name_plural': 'Venue Availabilities',
                'unique_together': {('venue', 'date')},
            },
        ),
    ]
