# Generated by Django 4.2.22 on 2025-06-08 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_venue_feature_and_room_models'),
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venueroom',
            name='venue',
        ),
        migrations.DeleteModel(
            name='VenueFeature',
        ),
        migrations.DeleteModel(
            name='VenueRoom',
        ),
    ]
