# Generated by Django 5.2.1 on 2025-06-08 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Course Categories',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Caterer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(help_text='Main cuisine specialty', max_length=255)),
                ('min_guests', models.PositiveIntegerField(default=10, help_text='Minimum number of guests for catering')),
                ('max_guests', models.PositiveIntegerField(default=500, help_text='Maximum number of guests for catering')),
                ('offers_buffet', models.BooleanField(default=True)),
                ('offers_plated', models.BooleanField(default=True)),
                ('offers_cocktail', models.BooleanField(default=True)),
                ('offers_food_stalls', models.BooleanField(default=False)),
                ('service_area', models.CharField(help_text='List of areas/cities served, comma separated', max_length=255)),
                ('setup_policy', models.TextField(blank=True)),
                ('delivery_policy', models.TextField(blank=True)),
                ('payment_policy', models.TextField(blank=True)),
                ('cancellation_policy', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caterer', to='accounts.providerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CatererImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='caterer_images/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('caterer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='caterers.caterer')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('is_gluten_free', models.BooleanField(default=False)),
                ('is_nut_free', models.BooleanField(default=False)),
                ('is_halal', models.BooleanField(default=False)),
                ('individual_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_item_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caterer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='caterers.caterer')),
                ('course_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='caterers.coursecategory')),
            ],
        ),
        migrations.CreateModel(
            name='MenuPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="E.g., 'Wedding Package A', 'Corporate Lunch Set'", max_length=255)),
                ('description', models.TextField()),
                ('package_type', models.CharField(choices=[('buffet', 'Buffet'), ('plated', 'Plated'), ('cocktail', 'Cocktail Reception'), ('food_stalls', 'Food Stalls'), ('mixed', 'Mixed Service')], max_length=15)),
                ('base_price_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_persons', models.PositiveIntegerField(default=10)),
                ('is_customizable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caterer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_packages', to='caterers.caterer')),
            ],
        ),
        migrations.CreateModel(
            name='CatererAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('morning_available', models.BooleanField(default=True)),
                ('afternoon_available', models.BooleanField(default=True)),
                ('evening_available', models.BooleanField(default=True)),
                ('max_bookings_per_day', models.PositiveIntegerField(default=1)),
                ('current_bookings', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('caterer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='caterers.caterer')),
            ],
            options={
                'verbose_name_plural': 'Caterer Availabilities',
                'unique_together': {('caterer', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection_limit', models.PositiveIntegerField(default=1, help_text='Number of items the customer can select from this category')),
                ('is_required', models.BooleanField(default=True)),
                ('additional_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('course_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caterers.coursecategory')),
                ('items', models.ManyToManyField(related_name='in_packages', to='caterers.menuitem')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_items', to='caterers.menupackage')),
            ],
            options={
                'unique_together': {('package', 'course_category')},
            },
        ),
    ]
