# Generated by Django 4.2.22 on 2025-06-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caterers', '0003_alter_caterer_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of this event type')),
                ('icon', models.CharField(blank=True, help_text='CSS icon class or emoji', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order for displaying event types')),
            ],
            options={
                'verbose_name': 'Event Type',
                'verbose_name_plural': 'Event Types',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='caterer',
            name='event_types',
            field=models.ManyToManyField(blank=True, help_text='Types of events this caterer specializes in', related_name='caterers', to='caterers.eventtype'),
        ),
    ]
