# Generated by Django 4.2.22 on 2025-06-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caterers', '0004_eventtype_caterer_event_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='caterer',
            name='service_name',
            field=models.CharField(default='Sample', help_text="Name of the catering service (e.g., 'Delicious Catering Co.')", max_length=255),
            preserve_default=False,
        ),
    ]
