# Generated by Django 4.2.22 on 2025-06-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caterers', '0005_caterer_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caterer',
            name='service_name',
            field=models.CharField(blank=True, help_text="Name of the catering service (e.g., 'Delicious Catering Co.'). Leave blank to use business name.", max_length=255),
        ),
    ]
