# Generated by Django 4.2.22 on 2025-06-08 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='venue_room',
        ),
    ]
