# Generated by Django 4.2.22 on 2025-06-11 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caterers', '0004_eventtype_caterer_event_types'),
        ('bookings', '0002_remove_venue_feature_and_room_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='event_type',
            field=models.ForeignKey(help_text='Type of event', on_delete=django.db.models.deletion.CASCADE, to='caterers.eventtype'),
        ),
    ]
